### PR TITLE
Automatic pipeline

### PR DESCRIPTION
**Pull request by gshukov98**

### CODE REVIEW

**Comment by gshukov98** [comment]
Hi, pipeline is ready

**Comment by gshukov98** [comment]
when you want to push new version in nuget
all that you must do is to create new tag with next version

**Comment by gshukov98** [comment]
image

**Comment by gshukov98** [comment]
This is example

**Comment by gshukov98** [comment]
The tag should be with bigger version than last and scheme is vX.Y.Z (v1.0.9) x is MAJOR version, y is MINOR and z is PATCH

**Comment by gshukov98** [comment]
and after you push this tag to origin version will be ready automatic

**Comment by gshukov98** [comment]
you can see the progress in actions tab in your repo

**Comment by gshukov98** [comment]
If you have any questions ask me :)

**Comment by Specter-13** [comment]
awesome, thank you

**Pull request merged**
